label: Aries Cloud Agent + Oracle Resolver

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: true

# Load toolbox plugin
plugin:
  - acapy_resolver_oracle

# Transport
inbound-transport:
  - [http, 0.0.0.0, 3000]
outbound-transport: http
endpoint:
  - http://localhost:3000
  - ws://localhost:3000

# Ledger
no-ledger: true

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true

# Credentials and Presentations
preserve-exchange-records: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true

auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true

# Wallet
wallet-name: default
wallet-type: indy
wallet-key: "insecure, for use in demo only"
auto-provision: true
